name: msm-Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Image Build
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 8
      matrix:
        device:
          # Exynos 7885
          - a10
          # Exynos 990
          - s20

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install required packages
        run: |
          sudo dpkg --add-architecture i386
          wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository ppa:cybermax-dexter/sdl2-backport
          sudo apt-add-repository "deb https://dl.winehq.org/wine-builds/ubuntu $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get -y install build-essential uuid-dev clang llvm iasl nasm gcc-aarch64-linux-gnu abootimg python3-distutils python3-pil python3-git gettext libgcc-s1:i386 libstdc++6:i386
          sudo apt-get install --install-recommends winehq-stable

      - name: Build an image for ${{ matrix.device }}
        run: ./build.sh --device ${{ matrix.device }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.device }}
          path: ./*.img
